# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: dbogatov/personal:dotnetcore

stages:
- build
- test
- release
- deploy

build:
  stage: build
  script:
  - cd src/EShop/
  - printf "{\"Version\":{\"GitHash\":\"%s\"}}" $CI_BUILD_REF > version.json
  - npm install
  - bower install --allow-root
  - gulp
  - dotnet restore
  - dotnet publish -c release
  - cp {appsettings,version}.json bin/Release/netcoreapp1.1/publish/
  artifacts:
    expire_in: 30 min
    paths:
    - src/EShop/bin/
  tags:
  - Docker

tidy:
  stage: test
  dependencies:
  - build
  before_script:
  - cd src/EShop/bin/Release/netcoreapp1.1/publish
  - dotnet EShop.dll </dev/null &>/dev/null &
  - sleep 30
  script:
  - curl -L http://localhost:5000 | tidy -config tidy.conf -e
  tags:
  - Docker
  
blc:
  stage: test
  dependencies:
  - build
  before_script:
  - cd src/EShop/bin/Release/netcoreapp1.1/publish
  - dotnet EShop.dll </dev/null &>/dev/null &
  - sleep 30
  script:
  - blc --filter-level 3 --input http://localhost:5000 -rog --exclude www.nginx.com
  tags:
  - Docker

dockerify:
  stage: release
  dependencies:
  - build
  before_script:
  - docker info
  script:
  - cd src/EShop
  - docker build -t registry.dbogatov.org/dbogatov/shevastreameshop .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push registry.dbogatov.org/dbogatov/shevastreameshop
  tags:
  - Shell
  
deploy:
  stage: deploy
  script:
  - curl --request POST 'https://push.dbogatov.org/api/push/dmytro/deploy' --data "project=ShevaStream"
  