# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: dbogatov/personal:dotnetcore

before_script:
  - cd src/EShop/
  - npm install
  - bower install --allow-root
  - gulp
  - dotnet restore
  - dotnet build
  - dotnet run </dev/null &>/dev/null &
  - sleep 30

tidy:
  type: test
  script:
  - curl -L http://localhost:5000 | tidy -config tidy.conf -e
  only:
  - master
  
blc:
  type: test
  script:
  - blc --filter-level 3 --input http://localhost:5000 -rog --exclude www.nginx.com
  only:
  - master