# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: dbogatov/personal:dotnetcore

tidy:
  type: test
  script:
  - echo "Hello world"
  only:
  - master
  