# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: dbogatov/personal:dotnetcore

build:
  stage: build
  script:
  - cd src/EShop/
  - npm install
  - bower install --allow-root
  - gulp
  - dotnet restore
  - dotnet publish -c release
  - cp {appsettings,version}.json bin/Release/netcoreapp1.1/publish/
  artifacts:
    paths:
    - src/EShop/bin/

tidy:
  type: test
  dependencies:
  - build
  before_script:
  - apt-get install -y tree
  - tree -a
  - dotnet src/EShop/bin/Release/netcoreapp1.1/publish/EShop.dll </dev/null &>/dev/null &
  - sleep 30
  script:
  - curl -L http://localhost:5000 | tidy -config tidy.conf -e
  
blc:
  type: test
  dependencies:
  - build
  before_script:
  - dotnet src/EShop/bin/Release/netcoreapp1.1/publish/EShop.dll </dev/null &>/dev/null &
  - sleep 30
  script:
  - blc --filter-level 3 --input http://localhost:5000 -rog --exclude www.nginx.com
