stages:
- build
- test
- release

build:
  image: dbogatov/docker-containers:dotnet-core-latest
  stage: build
  script:
  - printf "{\"Version\":{\"GitHash\":\"%s\"}}" $CI_BUILD_REF > src/version.json
  - ./build.sh
  artifacts:
    expire_in: 90 min
    paths:
    - src/bin/
  tags:
  - Docker

test-dotnet:
  stage: test
  image: dbogatov/docker-containers:dotnet-core-latest
  script:
  - export ASPNETCORE_ENVIRONMENT="Testing"
  - printf "{\"Version\":{\"GitHash\":\"%s\"}}" $CI_BUILD_REF > src/version.json
  - cd test
  - dotnet restore
  - ./test.sh | tee tests.out
  - "cat tests.out | grep 'Failed: 0.'"
  tags:
  - Docker

tidy:
  image: dbogatov/docker-containers:dotnet-core-latest
  stage: test
  dependencies:
  - build
  before_script:
  - export ASPNETCORE_ENVIRONMENT="Staging"
  - cd src/bin/release/netcoreapp1.1/publish/
  - dotnet shevastream.dll > /dev/null &
  - sleep 15
  script:
  - curl -Ls http://localhost:5555/ | tidy -e
  - curl -Ls http://localhost:5555/home/profile | tidy -e
  - curl -Ls http://localhost:5555/home/contact | tidy -e
  - curl -Ls http://localhost:5555/home/faq | tidy -e
  - curl -Ls http://localhost:5555/store/product | tidy -e
  - curl -Ls http://localhost:5555/store/product/1 | tidy -e
  - curl -Ls http://localhost:5555/store/cart | tidy -e
  - curl -Ls http://localhost:5555/blog | tidy -e
  - curl -Ls http://localhost:5555/blog/29 | tidy -e
  tags:
  - Docker
  
blc:
  image: dbogatov/docker-containers:dotnet-core-latest
  stage: test
  dependencies:
  - build
  before_script:
  - export ASPNETCORE_ENVIRONMENT="Staging"
  - cd src/bin/release/netcoreapp1.1/publish/
  - dotnet shevastream.dll > /dev/null &
  - sleep 15
  script:
  - blc --filter-level 3 --input http://localhost:5555 -rog --exclude "*linkedin.*"
  tags:
  - Docker

release:
  stage: release
  dependencies:
  - build
  script:
  - docker build -t registry.dbogatov.org/dbogatov/shevastream:$CI_BUILD_REF_NAME .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push registry.dbogatov.org/dbogatov/shevastream:$CI_BUILD_REF_NAME
  artifacts:
    paths:
    - docker-compose.yml
  tags:
  - Shell
