stages:
- build
- dockerify
- test
- release
- deploy

before_script:
- export RELEASE_IMAGE="registry.dbogatov.org/dbogatov/shevastream:$CI_BUILD_REF_NAME"
- export TEST_IMAGE="$RELEASE_IMAGE-build"
- export DOTNET_TAG="$CI_BUILD_REF_NAME-build"

build:
  image: dbogatov/docker-containers:dotnet-core-latest
  stage: build
  script:
  - printf "{\"Version\":{\"GitHash\":\"%s\"}}" $CI_BUILD_REF > src/version.json
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - src/bin/
  tags:
  - Docker

dockerify:
  stage: dockerify
  dependencies:
  - build
  before_script:
  script:
  - docker build -t $TEST_IMAGE .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push $TEST_IMAGE
  tags:
  - Shell

test-dotnet:
  stage: test
  image: dbogatov/docker-containers:dotnet-core-latest
  script:
  - printf "{\"Version\":{\"GitHash\":\"%s\"}}" $CI_BUILD_REF > src/version.json
  - cd test
  - dotnet restore
  - ./test.sh | tee tests.out
  - "cat tests.out | grep 'Failed: 0.'"
  tags:
  - Docker

tidy:
  image: dbogatov/docker-containers:dotnet-core-latest
  stage: test
  dependencies:
  - build
  before_script:
  - cd src/bin/release/netcoreapp1.1/publish/
  - dotnet shevastream.dll > /dev/null &
  - sleep 5
  script:
  - curl -Ls http://localhost:5555/ | tidy -e
  # - curl -Ls http://localhost:8080/academics.html | tidy -e
  # - curl -Ls http://localhost:8080/contacts.html | tidy -e
  # - curl -Ls http://localhost:8080/feedback.html | tidy -e
  # - curl -Ls http://localhost:8080/portfolio.html | tidy -e
  # - curl -Ls http://localhost:8080/resume.html | tidy -e
  tags:
  - Docker
  
blc:
  image: dbogatov/docker-containers:dotnet-core-latest
  stage: test
  dependencies:
  - build
  before_script:
  - cd src/bin/release/netcoreapp1.1/publish/
  - dotnet shevastream.dll > /dev/null &
  - sleep 5
  script:
  - blc --filter-level 3 --input http://localhost:5555 -rog --exclude "*linkedin.*"
  tags:
  - Docker

release:  
  stage: release
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker pull $TEST_IMAGE
  - docker tag $TEST_IMAGE $RELEASE_IMAGE
  - docker push $RELEASE_IMAGE
  tags:
  - Shell
