version: '2' # defualt is 1. v1 will be deprecated
services:
  nginx:
    image: nginx:latest
    ports: # publish HTTP and HTTPS ports
      - 8888:80
      - 4430:443
    links:
      - "dotnet:mysite"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dotnet
  dotnet: # without image, compose will take Dockerfile from this direactory and build it (at least it should)
    image: registry.dbogatov.org/dbogatov/shevastream:${DOTNET_TAG} # if DOTNET_TAG not set, use "", or :latest
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - postgres
    links:
      - "postgres:database"
    restart: on-failure
  postgres:
    image: postgres:latest
    environment: # define connection credentials to be used in app
      - POSTGRES_DB=shevastream
      - POSTGRES_USER=shevastream
      - POSTGRES_PASSWORD=SomethingWeird15
